### ISSUE TITLE
"uncaught exception: undefined undefined"

### ISSUE THREAD

**Issue by mhmmsips** [ChristianLisle/memory-download#24]
When using the installer or the executable file for windows, an error occurs. The tool is not useable because of this error.

![Screenshot 2022-01-24 120902](https://user-images.githubusercontent.com/94537410/150772185-eaeb6675-2ea1-422c-9c8e-c96008d80790.jpg)

**Comment by ChristianLisle** [comment]
@mhmmsips Could you try running the latest version of the application again? I believe I have resolved this. It was an issue where the library, `ffmpeg-installer` was not configured for all platforms correctly.

**Comment by ChristianLisle** [comment]
No worries. I'm glad it's working now 😁
