### ISSUE TITLE
Add ESLint and Prettier for linting and formatting

### ISSUE THREAD

**Issue by abhideepm** [ChristianLisle/memory-download#62]
- ESLint is for linting the project.
- Prettier is for standardizing the styling across the project.
- Also will reformat the whole project after adding the prettier support.

**Comment by abhideepm** [comment]
Assign it to me please, will work on this before #60.

**Comment by ChristianLisle** [comment]
I was literally just about to create an issue for this 😆 

I've got some preferences on eslint rules and prettier, so I'll take this one. \
I'll open a PR and request your review shortly after #61 is merged in.

**Comment by ChristianLisle** [comment]
Check your inbox for an invite
